// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2025 Autonomy / OpenPLC Project
// AUTO-GENERATED by scripts/rebuild-libs.mjs from package.json. Do not edit by hand —
// any changes are overwritten on the next build.
export const STRUCPP_VERSION_BUILD = "0.6.1";
